from transformers import AutoTokenizer, AutoModelForCausalLM, pipeline
import json
import os
import torch

# Model configuration
MODEL_NAME = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
HF_TOKEN = os.getenv("HF_TOKEN")  # optional

# Load tokenizer and model (CPU):
tokenizer = AutoTokenizer.from_pretrained(
    MODEL_NAME,
    token=HF_TOKEN
)
# AutoModel automatically detects model architecture for model loading:
# AutoModelForCausalLM is for text generation:
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    device_map=None,
    dtype=torch.float32,
    token=HF_TOKEN
)

generator = pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer,
    device=-1,  # CPU only
    max_new_tokens=600,
    temperature=0.2,
    eos_token_id=tokenizer.eos_token_id
)

# JSON extractor
def extract_json(text: str) -> dict:
    try:
        start = text.index("{")
        end = text.rindex("}") + 1
        return json.loads(text[start:end])
    except Exception:
        # Safe fallback to prevent crashes
        return {
            "site_type": "landing",
            "theme": "light",
            "meta": {
                "title": "Generated Website",
                "description": "AI generated website"
            },
            "components": {
                "Hero": {
                    "headline": "Welcome",
                    "subtext": "Website generated by AI"
                }
            }
        }

# JSON spec generator
def generate_spec(prompt: str) -> dict:
    prompt_text = f"""
You are a JSON generator.

Output ONLY valid JSON.
No explanations.
No markdown.
No extra text.

Schema:
{{
  "site_type": "",
  "theme": "light or dark",
  "meta": {{
    "title": "",
    "description": ""
  }},
  "components": {{
    "Hero": {{
      "headline": "",
      "subtext": ""
    }}
  }}
}}

User request:
{prompt}

JSON:
"""

    output = generator(prompt_text)[0]["generated_text"]

    print("RAW MODEL OUTPUT:\n", output)

    return extract_json(output)
